In [1]:
import numpy as np

In [14]:
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
print(a)
print(b)


[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [15]:
type(a)

numpy.ndarray

OPERATIONS AND METHODS

In [16]:
print(a+b)
print(a-b)
print(a*b)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]


In [ ]:
#Creating a 2D Array=Two 1D Array
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Creating a 3D Array= Two 2D Array
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(a2.shape) #2D=rows,columns
print(a3.shape) #3D=no.of matrices,rows,coluumns

(2, 3)
(2, 2, 3)


In [24]:
print(a3.ndim)

3


In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.random.randint(1,21,size=(3,4)) #used toconstruct 2D Array with given(rows,columns)

array([[ 2,  6, 12,  3],
       [ 2, 11,  5, 20],
       [14,  9,  6,  1]], dtype=int32)

In [31]:
x=np.array([[7,2,3],[3,4,5],[3,5,1]])
y=np.array([[7,5,3],[3,4,7],[3,3,1]])
print(x)
print(y)

[[7 2 3]
 [3 4 5]
 [3 5 1]]
[[7 5 3]
 [3 4 7]
 [3 3 1]]


In [32]:
print(x*y)

[[49 10  9]
 [ 9 16 35]
 [ 9 15  1]]


In [33]:
print(x@y)

[[64 52 38]
 [48 46 42]
 [39 38 45]]


In [ ]:
x.dot(x,y) #same as @

array([[64, 37, 34],
       [48, 47, 34],
       [39, 31, 35]])

In [34]:
x.mean()

np.float64(3.6666666666666665)

In [36]:
round(x.mean())

4

In [37]:
print(x.sum())
print(x.var())
print(x.std())


33
2.888888888888889
1.699673171197595


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,25))  #25th Percentile=25% of data is before 3(from output)
print(np.percentile(arr,50))  #50th Percentile=50% of data is before 5(from output)
print(np.percentile(arr,75))  #75th Percentile=75% of data is before 7(from output)

3.0
5.0
7.0
