### Numpy
1. Write a NumPy program to create an array of 10 zeros.

2. Write a NumPy program to create an array of 10 ones.

3. Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

4. Write a NumPy program to reverse an array (first element becomes the last).

5. Write a NumPy program to extract all odd numbers from an array.

6. Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

7. Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

9. Write a NumPy program to multiply two given matrices.

10. Write a NumPy program to find the unique elements of an array.

11. Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

12. Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

13. Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

14. Write a NumPy program to reverse the order of elements in each column of a 2D array.

15. Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [4]:
import numpy as np

In [27]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
a=np.array([1,2,3,4,5,6,7,8,9])
reversed_a=a[::-1]
print(reversed_a)

[9 8 7 6 5 4 3 2 1]


In [31]:
a=np.array(list(map(int,input("ENter the numbers").split())))
b=np.array(list(filter(lambda x: x%2!=0,a)))
print(a)
print(b)

[1 5 9 3 5 7]
[1 5 9 3 5 7]


In [6]:
a=np.array(list(map(int,input("Enter the number separated by space").split())))
b=sum(a)
mean=b/len(a)
sd=np.std(a)
print(b)
print(mean)
print(sd)



53
5.3
2.6095976701399777


In [ ]:
a=np.random.random((5,5))
print(a)
print("Maximum value is" ,a.max())
print("Minimum value is" ,a.min())

[[0.53722461 0.21166994 0.49017704 0.09410987 0.43052757]
 [0.80059006 0.77490876 0.81011964 0.79059431 0.47693396]
 [0.41311343 0.27101672 0.35719504 0.59794107 0.78935282]
 [0.42992911 0.78336088 0.15871423 0.35755728 0.85676984]
 [0.5206059  0.2747119  0.25876745 0.35684941 0.55739187]]
Maximum value is 0.8567698420764285
Minimum value is 0.09410986743451444


In [20]:
r,c=5,5
a=np.zeros((r,c),dtype=int)
a[0,:]=1
a[-1:]=1
a[:,0]=1
a[:,-1]=1
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [27]:
a=np.random.randint(1,20,size=(2,2))
b=np.random.randint(1,20,size=(2,2))
c=a*b
d=a@b
print("Maatrix is \n",a)
print("Maatrix is \n",b)
print("Normal Multiplication is \n ",c)
print("Matrix Multiplication is \n ",d)
print(d)

Maatrix is 
 [[17 10]
 [19  4]]
Maatrix is 
 [[ 4 16]
 [ 5 10]]
Normal Multiplication is 
  [[ 68 160]
 [ 95  40]]
Matrix Multiplication is 
  [[118 372]
 [ 96 344]]
[[118 372]
 [ 96 344]]


In [34]:
a=np.array(list(map(int,input("Enter the number separated by space").split())))
b=np.array(list(map(int,input("Enter the number separated by space").split())))
unique_element=set(a)&set(b)
c=[int(i) for i in a if i not in unique_element]
print(c)
c=np.array(c)
type(c)

[1, 2, 3]


numpy.ndarray

In [40]:
a=np.array(list(map(int,input("Enter the number separated by space").split())))
b=np.array(list(filter(lambda x: x%2!=0,a)))
print(b)

[1 3 5]


In [42]:
a=np.array(list(map(int,input("Enter the number separated by space").split())))
b=np.array(list(filter(lambda x: x%2==0,a)))
print(b)

[2 4 6]
